### ISSUE TITLE
[Request] CM 12, Google Now and facets wallpapers

### ISSUE THREAD

**Issue by M2ck** [DirtyUnicorns/Papuh-Resources#33]
Previously requested [here](https://github.com/Papuh/PapuhWalls/issues/29#issuecomment-162311098), could you add [CM Material](https://github.com/CyanogenMod/android_packages_apps_CMWallpapers/commit/b684222ef59ab60f92b5e047b2eafacf46b89678), [Google Now](https://plus.google.com/+AtharvaWashimkar/posts/irFamm4rAPV) and [Facets](http://www.facets.la/) Wallpapers please?
If it's not possible due to license or other, please create wallpapers based on them.
Thanks for this great open source app!

N.B: I'm not a developer, I don't know make such pull request. That's why I post here.

**Comment by nychitman1** [comment]
Get us the links to where these images are stored for proper credit and we'll see what we can do. Otherwise, do not post here.

**Comment by M2ck** [comment]
Links already there, just updated Google Now link.

**Comment by nychitman1** [comment]
GJ
